### ISSUE TITLE
Footer Bar is not showing

### ISSUE THREAD

**Issue by alxrtega** [alxrtega/AlexOrtegaWorks#2]
The footer bar is not showing in the web app.

**Comment by KevinApodaca** [comment]
I believe the reason for this is because of your `v-show` in FooterBar.vue. You set the conditional variable `isFooterBarVisible`

But you never make that variable true in your other pages, so it never shows.

To fix it, either:

- remove the `v-show` on the footer component 
- set the variable to true in your pages using the `data` lifecycle hook

https://recordit.co/HrmLFrTRrQ
